### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ghost** [SuSonicTH/micro-transform#1]
It is not possible to install the plugin using repo.json, I believe it must be because the version Url is not the one that contains the plugin's zip file, it could be resolved by creating a tag through git and pushing it to github so the zip url can be found at https://github.com/SuSonicTH/micro-transform/archive/<version\>.zip.

It would basically be the commands below but see the links for more details:
```sh
git tag \
  -a "0.1.0"         # version \
  -m "Release 0.1.0" # message
git push --tags  # publish the tags

```

## How to Test? 

To test the installation, follow the steps below:

### Settings

Add this repo as a **pluginrepos** option in the
**~/.config/micro/settings.json** file
(it is necessary to restart the micro after this change):

```json
  "pluginrepos": [
    "https://raw.githubusercontent.com/SuSonicTH/micro-transform/master/repo.json"
]
```

### Install

In your micro editor press **Ctrl-e** and run command:

```
> plugin install transform
```

or run in your shell

```sh
micro -plugin install transform
```

---

Refs:
- https://git-scm.com/book/en/v2/Git-Basics-Tagging
- https://docs.github.com/en/desktop/managing-commits/managing-tags-in-github-desktop

**Comment by SuSonicTH** [comment]
Hi taconi,

thanks for the hint! I installed all my plugins manually so I didn't know/care about the plugin manger.
I added a tag and changed the repo.json to point to the zip. Plugin installation worked for me, can you please try it out?

Cheers,
Micahel

**Comment by ghost** [comment]
everything ok for me
